# Generated by Django 5.0 on 2026-04-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('dataNaix', models.DateField()),
                ('telefon', models.IntegerField()),
                ('codiPostal', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('rol', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Admin', 'Admin'), ('Visitant', 'Visitant')], max_length=30)),
                ('document', models.CharField(choices=[('NIE', 'Nie'), ('DNI', 'Dni'), ('PASSPORT', 'Passport')], max_length=15)),
            ],
        ),
    ]
