# Generated by Django 5.0 on 2026-04-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='numDoc',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='person',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
