# Generated by Django 5.0 on 2026-04-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_person_numdoc_alter_person_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='numDoc',
            field=models.CharField(max_length=9),
        ),
    ]
