# Generated by Django 5.0 on 2026-04-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_person_numdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='codiPostal',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='telefon',
            field=models.IntegerField(max_length=9),
        ),
    ]
