# Generated by Django 5.0 on 2026-04-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_person_codipostal_alter_person_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='codiPostal',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='telefon',
            field=models.CharField(max_length=9),
        ),
    ]
